apiVersion: v1
kind: Secret
type: Opaque # 범용

# Secret 기본 정보
metadata:
  name: my-app-secrets # Secret 이름

# Key, Value 형식으로 값 저장
stringData:
  DB_HOST: my-database-lcy.c3qme6c6e7fj.ap-northeast-2.rds.amazonaws.com
  DB_PORT: "3306"
  DB_NAME: testdb
  DB_USERNAME: admin
  DB_PASSWORD: password